# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "byVbfKE0WHtgrLbsnsrP2bVLZ55w/N7WRE//03KMqFg5aE11su3g1GUzUv4on/UIEeqAuRzUGX6fel9SACWDinna082EYstPy9VtRPqe8TDGMqKPzByRUnav71ZCM9dun3lXtyqpgB8SJbMd6XjqXBPDMShzGWS2DS92kHhdKFfzLQHMWPonQPOTDZBpPvO6q30ifddITpG4aOsESnaAmgu0BXVPuYA1n9aftgDToLcBGrDYjdowSIluSU5CNG8gBt+b33wOuB8z9mm4+cJ7773fEtHn+hBKeApr5Iapc78Rlh/fySOBLeZSIexA1jhLD/aEvvtx3Qn+4el87sDD2cQEPeWHk31OPzB6FHq9XYhkpu/P6XHlB2Q99Xq6hWTvCB44McbBgMh9Uyfh+IRjTPY8SVXRbnPmm9FnW/Fj6PA4ZAZiOlSG0E3Bt4zFYN82YHZ+bNpHKgzrtwS0OFcGqupfqC2M5mOqTjBLBU0OYvze3qR3vAW6ujHZD3iZtsuVJbrspoGAZI7595rzAUXc1lOZWDCmhNnz+Lpl93QqFnQtHIcl8ElbSqh2NUXZOTJMCj9/YcoQOL2/QWfcC4A4Ewnd3jcVBqQnQxo/8hpbrvvExhB5+P+TESHmryyRGaoxwJGbNeMajXaRDJWQRlM2icpsbMESFikHR4tdaX1Lb+M="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
