travis:
  secure:
    BINSTAR_TOKEN: byVbfKE0WHtgrLbsnsrP2bVLZ55w/N7WRE//03KMqFg5aE11su3g1GUzUv4on/UIEeqAuRzUGX6fel9SACWDinna082EYstPy9VtRPqe8TDGMqKPzByRUnav71ZCM9dun3lXtyqpgB8SJbMd6XjqXBPDMShzGWS2DS92kHhdKFfzLQHMWPonQPOTDZBpPvO6q30ifddITpG4aOsESnaAmgu0BXVPuYA1n9aftgDToLcBGrDYjdowSIluSU5CNG8gBt+b33wOuB8z9mm4+cJ7773fEtHn+hBKeApr5Iapc78Rlh/fySOBLeZSIexA1jhLD/aEvvtx3Qn+4el87sDD2cQEPeWHk31OPzB6FHq9XYhkpu/P6XHlB2Q99Xq6hWTvCB44McbBgMh9Uyfh+IRjTPY8SVXRbnPmm9FnW/Fj6PA4ZAZiOlSG0E3Bt4zFYN82YHZ+bNpHKgzrtwS0OFcGqupfqC2M5mOqTjBLBU0OYvze3qR3vAW6ujHZD3iZtsuVJbrspoGAZI7595rzAUXc1lOZWDCmhNnz+Lpl93QqFnQtHIcl8ElbSqh2NUXZOTJMCj9/YcoQOL2/QWfcC4A4Ewnd3jcVBqQnQxo/8hpbrvvExhB5+P+TESHmryyRGaoxwJGbNeMajXaRDJWQRlM2icpsbMESFikHR4tdaX1Lb+M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
