travis:
  secure:
    BINSTAR_TOKEN: KqcoQ2w53aBFUcX3Kb0qEuAeMSUuzd0WvSUVqNuAWZPPxRPxYmw9j2dsX7wU6j2q0OAXZVa0B8vIqDGXcapZ/of54LibDbOt2pSnlQ8015dXVoYnKhAscJd+1gFpmWMu8djvx8l+wme+OF46D2kg7pspNgmBx2PLmQlF6qwWOlHIg9NJazL2c+Dvga/zMmhsE+/GgqcYDfHeDCafXWzlBgkwRBVOKGYsZd2BxTqemHdXe1GwFwJcThxO+gsf8NauWLMqske5BQsnfnUsthLeYefFJBQVmq69ysaqp5ICTcAhE5NmOEmG5I+J5kTn5kzlt68k2Us69TRt6I8+3Bkc/RdaVAmO0Q4uLYi1sRZ4ovhweNhsSFzZJpZAoxqmJiFR8OVZYv0Ud+bB8Wbb8RwuvDOYXdRm8uaznxLVQV/Cc+2xIjO3KzGifAISG+wpWRrQhzO3aXFR7hqKmmLlSV+K4dnIgyiC7zFDEqRdWo84PUlZttE6ymubX4Yyz5ooeVdGtbyWpEY+USF5vCVdMevP7ZVo6nKdbL8vUE3a7rcT/B2kuWiFnfP4bS4KS72BvI8wSXeoUem1TLnRB/wFIlLxTBUkNJQsKDurauzZ5pYDe5olFJSRC3LK8Eb142MBzTJ3sDT5NdSTVd7bMKSpwLhdFx0CQu5KYvwGx6O3QDS5oUU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
